### ISSUE TITLE
tooltip issues

### ISSUE THREAD

**Issue by nightw0lv** [thomaspark/bootswatch#1079]
this is how it works
```data-toggle="tooltip" data-bs-placement="right" data-bs-html="true" title="<i>my html title</i>"```
this is how it should work on v5 according to their website
```data-bs-toggle="tooltip" data-bs-placement="right" data-bs-html="true" data-bs-original-title="<i>my html title</i>"```

https://getbootstrap.com/docs/5.0/components/tooltips/

notes: i tried with bootstrap.bundle.js no luck so i am using external tooltip library if you want to replicate it

**Comment by thomaspark** [comment]
Hey @nightw0lv, are you talking about the markup you get when you open the code modal for tooltips on a preview page like so?

<img width="1191" alt="Screen Shot 2021-02-16 at 5 44 53 PM" src="https://user-images.githubusercontent.com/900407/108131052-b3395000-707e-11eb-888c-f1654ad4f83a.png">

I see the code differs from the markup in the official docs. This is because it pulls from the component's own markup, which has been modified by Bootstrap's js.

If so, a workaround could be implemented to keep the original markup for purposes of the modal. This also affects v4.

**Comment by nightw0lv** [comment]
hello, thank you for the response, i also noticed in v5 that if i move the mouse over a button 1-2 times tooltip flash disappears immediately and never shows again, i am noob and i might be not explaining it correctly i try to follow the template codes

**Comment by nightw0lv** [comment]
@thomaspark note that this behavior is still there http://prntscr.com/zy2cai
the normal first level html tag will work
the childs cause the tooltip to disappear if inside the first tag are more tags or more tooltips (i know is overextended topic on tooltips but if you can fix this i will be glad) i am closing since it works as expected but please consider my noting for deeper use.

**Comment by thomaspark** [comment]
Hey @nightw0lv, I see, so nested tooltips stop working after the first few hovers? Most likely you'll see this bug with vanilla Bootstrap as well. I recommend opening an issue upstream with them.

**Comment by nightw0lv** [comment]
@XhmikosR 
i found this https://github.com/twbs/bootstrap/issues/32372
and this https://github.com/twbs/bootstrap/issues/31646

i am just tagging you in case here you see something new that might help your investigations

- Καλημέρα :)

**Comment by XhmikosR** [comment]
The issue is still open upstream, but patches are welcome. We have a potential PR open but it doesn't totally fix the issue.
