### ISSUE TITLE
Problems with certain themes

### ISSUE THREAD

**Issue by rweas** [thomaspark/bootswatch#370]
I don't know if these are just for my installation or what, however most of the themes work, but these don't:
**Paper:**

    [14:33:58] gulp-notify: [Laravel Elixir] Error: /Users/russellweas/Desktop/Laravel/Buzzer/vendor/bower_components/bootswatch-sass/paper/bootswatch:40: error: error reading values after "default"

**Sandstone:**
    [14:34:40] gulp-notify: [Laravel Elixir] Error: /Users/russellweas/Desktop/Laravel/Buzzer/vendor/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/forms:52: error: argument `$color` of `red($color)` must be a color
    Backtrace:
	 /Users/russellweas/Desktop/Laravel/Buzzer/vendor/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/forms:52, in function `red`
	/Users/russellweas/Desktop/Laravel/Buzzer/vendor/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/forms:52, in mixin `form-control-focus`
	/Users/russellweas/Desktop/Laravel/Buzzer/vendor/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/forms:131

**Superhero:**
    [14:35:29] gulp-notify: [Laravel Elixir] Error: /Users/russellweas/Desktop/Laravel/Buzzer/vendor/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/forms:52: error: argument `$color` of `red($color)` must be a color
    Backtrace:
	/Users/russellweas/Desktop/Laravel/Buzzer/vendor/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/forms:52, in function `red`
	/Users/russellweas/Desktop/Laravel/Buzzer/vendor/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/forms:52, in mixin `form-control-focus`
	/Users/russellweas/Desktop/Laravel/Buzzer/vendor/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/forms:131

Superhero looked really cool, if I can get it figured out I will be excited to be adding it to my project! Thanks for making so many cool free themes, I'm going to be looking into this and making a pull request if I figure it out.

**Comment by VladShcherbin** [comment]
Ok, I've tested all the themes in sass

**Paper** - transparent color error
**Sandstone** - transparent color error
**Superhero** - transparent color error

> **gulp-sass** uses **node-sass** and **node-sass** uses **libsass**

**Transparent color error** - variables with the transparent color caused the libsass error.
[libsass issue](https://github.com/sass/libsass/issues/700), fixed in libsass > 3.0.2 (current 3.1).
node-sass latest version (1.2.3) doesn't use 3.1, so we have to wait node-sass 2.0 (in beta now).
then gulp-sass will use node-sass 2.0 and bump version (to 1.2.5 or 2.0) and it will be ok.

So, **it is the libsass issue**, not the bootswatch. Can be closed.

**Comment by rweas** [comment]
OK cool. Thanks for the research!
