### ISSUE TITLE
Missing subset for czech language

### ISSUE THREAD

**Issue by juniwalk** [thomaspark/bootswatch#412]
Some of the themes have problems with the Czech Language, characters like "šřžů" look different (fallback font).

For most, if not all fonts this can be fixed by including '&subset=latin-ext' in the font url.

This will increase the load time of the font, best way would be to provide API links to font and minified cdn css separately so I could modify font url.

**Comment by thomaspark** [comment]
So if I understand correctly, you're suggesting to remove the font import statement from css so it can be declared separately?

This would reduce convenience for the majority of users, and I'd rather not support both as it starts to get complicated in terms of both maintenance and ux.

I don't know of a way to handle this otherwise besides manually changing the URL or adding a second, redundant import statement with latin-ext in your own html or css.

**Comment by nicolasmccurdy** [comment]
> ... or adding a second, redundant import statement with latin-ext in your own html or css.
I would recommend this. It's slower, but it makes it easier for people to use Bootswatch and easier for you to update it without conflicts.

**Comment by juniwalk** [comment]
Would it at least be possible to leave css as is and provide the font url in the API as an addition? I have a snippet which allows user to switch themes of my website using those from bootswatch api, CSS is then loaded using cdn link. It would be kinda hard to modify font urls in this scenario.

If you provide font url additionaly I can atleast use that redundant import statement.
