### ISSUE TITLE
Readable theme  in ie8 

### ISSUE THREAD

**Issue by Syses** [thomaspark/bootswatch#436]
when i use  ie8 and readable theme,the navbar will over height.just like the follow image
![ie8_readable](https://cloud.githubusercontent.com/assets/7549358/7060982/6f749c84-debd-11e4-9b6b-b1a96e5f43e2.JPG)
![ie8_readable2](https://cloud.githubusercontent.com/assets/7549358/7060996/b49ecd8e-debd-11e4-88b1-6ad72723dc87.JPG)

**Comment by thomaspark** [comment]
Can you post a screenshot of what http://bootswatch.com/readable/ looks like on your setup, as well as your navbar code or link to your page?

**Comment by Syses** [comment]
when i open  http://bootswatch.com/readable/  ,and i run command {{  $(".container").eq(1).prepend('<div class="breadcrumb"><a href="#">Main</a> » Request search</div>'); }}
the  IE11,IE8,chrome screenshot  is bellow

![Uploading chrome1.JPG . . .]()
![Uploading IE11.JPG . . .]()
![Uploading IE8.JPG . . .]()

**Comment by Syses** [comment]
hello park ,i send a mail to you !!! please check it

**Comment by thomaspark** [comment]
Turns out to be an issue with respond.js. Basically, earlier media queries override later styles, even when they shouldn't take precedence (see https://github.com/scottjehl/Respond/issues/225).

In this case, a later padding rule on navbar elements is being overridden by an earlier media query. I'll fix this (hackily) by giving it its own media query.
