### ISSUE TITLE
Define sass variables with !default

### ISSUE THREAD

**Issue by sirianni** [thomaspark/bootswatch#450]
It would be nice to allow selective overriding of bootswatch SASS variables (much like bootstrap does), by using the `!default` qualifier.

**Comment by jaywilliams** [comment]
:+1: Yes, I was going to suggest the very same thing. This should be a fairly strait forward. If you'd like me to make a pull request, just let me know.

**Comment by thomaspark** [comment]
What happens if you set multiple `!default` qualifiers for the same variable — last one wins?

A pull request would be welcome. To implement this, you'd need to update the regex in the Grunt task that converts LESS -> SASS:

https://github.com/thomaspark/bootswatch/blob/gh-pages/Gruntfile.js#L202-L240

**Comment by jaywilliams** [comment]
According to the SASS Manual:
> You can assign to variables if they aren’t already assigned by adding the !default flag to the end of the value. This means that if the variable has already been assigned to, it won’t be re-assigned, but if it doesn’t have a value yet, it will be given one.

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_

In other words, it's perfect for cases when you want to override styles from a package, without actually changing the package itself (i.e. Bower).

**Comment by thealjey** [comment]
This is one of the main advantages of SASS over LESS, it reduces the duplication significantly.
Specifically this particular feature makes copying the whole contents of **_variables.scss** (what bootswatch unfortunately does right now) completely unnecessary, you only define what needs to be changed, and since bootstrap-sass already uses **"!default"** throughout, your changes will be picked up and not overwritten.

**Comment by jaywilliams** [comment]
I just submitted a pull request with this change in place. Please review the code and let me know if you'd like any changes. I tried to follow the same coding style and format.
