### ISSUE TITLE
lib has old version (v3.3.2) of /flatly on npm 

### ISSUE THREAD

**Issue by hyzhak** [thomaspark/bootswatch#475]
I just get last version of `bootswatch` from npm. By
```
npm install bootswatch --save-dev
```
It is 3.3.4. But if you check /flatly/bootstrap.css version in comment is 3.3.2
```javascript
/*!
 * bootswatch v3.3.2
 * Homepage: http://bootswatch.com
 * Copyright 2012-2015 Thomas Park
 * Licensed under MIT
 * Based on Bootstrap
*/
```
and 
`/flatly/variables.less` still have old bug absent of `;` after `@form-group-margin-bottom:       15px`.

As result I can't use `/flatly/variables.less` right now because it lack of `;`.

It seems that you should do 
```
npm publish bootswatch
```
to update lib on `npm`.

**Comment by thomaspark** [comment]
Unfortunately it's not possible to republish to the same version number, and npm doesn't account for build numbers (e.g., v3.3.4+1), so I don't see any way around it until the next version.

In the meantime, you can install a specific hash, or use bower to install bootswatch since it does factor in the build number.

**Comment by hyzhak** [comment]
when do you plan to release next version?

**Comment by thomaspark** [comment]
The version numbers are in sync with Bootstrap, so would tick with the next Bootstrap release.
