### ISSUE TITLE
Change current file structure

### ISSUE THREAD

**Issue by idleberg** [thomaspark/bootswatch#487]
I'm currently using Gulp to download Bootswatch via npm and iterate over all included themes. However, the current file structure forces me to check against some exceptions which doesn't make it very future proof.

bootswatch
--~~2~~
--~~api~~
--~~assets~~
--~~bower_components~~
--cerulean
--cosmo
--custom
--cyborg
--darkly
--~~default~~
--flatly
--~~global~~
--~~help~~
--journal
--lumen
--paper
--readable
--sandstone
--simplex
--slate
--spacelab
--superhero
--~~tests~~
--united
--yeti

While this is a very specific problem, it's probably not too far fetched to think that others might want to do something like that. Anyway, I think it's good practice to separate themes from the other folders.

**Comment by thomaspark** [comment]
Agree it's good practice to separate the themes. The reason I had things organized this way is because I use `gh-pages` branch to host the site, and wanted the themes available at bootswatch.com/theme/. The themes also expect glyphicons at `../fonts/`.

What if there was a JSON file that maintained a list of themes? It could be used for the grunt tasks as well. `api/3.json` can already can kind of serve this purpose.

**Comment by idleberg** [comment]
> What if there was a JSON file that maintained a list of themes? It could be used for the grunt tasks as well.

Sounds good!

**Comment by thomaspark** [comment]
How about I just add a 'folder' property to `api/3.json`?

**Comment by idleberg** [comment]
I didn't have a look at `api/3.json` until now, but this (plus `toLowerCase()`) would indeed serve the purpose. Unless you have some **ẘḛïȑḋ™** naming ideas for the future themes, that would have to be stored in a more safely named folder 😉

**Comment by thomaspark** [comment]
If `themes[i].name.toLowerCase()` works for you, I'll leave it unchanged for now. No plans for a ẘḛïȑḋ™ new theme, but you never know...
