### ISSUE TITLE
Webpack Support

### ISSUE THREAD

**Issue by saulshanabrook** [thomaspark/bootswatch#492]
I figured out that to import the files from the npm installed module in webpack requires a bit of effort, so I [wrote up a blog post](http://www.saulshanabrook.com/bootswatch-in-webpack/). I am adding this as an issue in case anyone else also had the same question and searched for it here.

**Comment by thomaspark** [comment]
Thanks for sharing this!

**Comment by stevepiercy** [comment]
I must be missing something. I followed the instructions in the blog post. There's no explicit example of what needs to go in `webpack.config.js`, except "enable the less loader". @saulshanabrook can you elaborate? Thanks for any help.

**Comment by saulshanabrook** [comment]
@stevepiercy Sure! [Here is an example](https://github.com/webpack/less-loader#webpack-config) for how to enable the less loader for less files.

Other than that, webpack should be set up to process your JS files correctly. [I just found this guide](https://christianalfoni.github.io/react-webpack-cookbook/index.html) on setting up Webpack for development with React (which should be applicable even if you are not using React).

[This](https://github.com/lucibus/lucibus/blob/086e9bccc979d92e9a74005a57c0ca577d8514ab/caido/webpack.config.js) is what my config looks like. It was built from [react-starter](https://github.com/webpack/react-starter) with a lot removed and added.

Let me know if you need any other help.

**Comment by stevepiercy** [comment]
@saulshanabrook Thank you! I've made some progress. I'm trying to build static assets for deployment.

What does the tilde/twiddle ~ symbol represent in the import statement?
```
@import "~bootstrap/less/bootstrap.less";
```
The module's path cannot be resolved with that syntax.
```
ERROR in ./~/css-loader!./~/less-loader!./_app/bootswatch.less
Module build failed: Cannot resolve module 'bootstrap/less/bootstrap.less' in /Users/stevepiercy/projects/webpack-bootswatch/_app
```
This got past the import error.
```
@import "../node_modules/bootswatch/bower_components/bootstrap/less/bootstrap.less";
@import "../node_modules/bootswatch/readable/variables.less";
@import "../node_modules/bootswatch/readable/bootswatch.less";
```
Which then leads to how to handle the font files.

**Comment by saulshanabrook** [comment]
@stevepiercy I dont know what the tilde is, I think I saw it somewhere else.

Can you import other resources from your `node_modules` folder? Like JS libraries?

That just works by default for me, if you change dhte [modulesDirectory](http://webpack.github.io/docs/configuration.html#resolve-modulesdirectories), maybe then it isn't finding things. My advice would be to start with a [starter project](https://github.com/webpack/react-starter) and make sure that works. Then remove features individually, making sure after you remove a feature it still works. For example, I took that repo and removed all the isomorphic code.

There are a lot of reasons why something doesn't work, so it is hard to diagnose all of them. It is much easier to start with something working and then hack on it, I have found.

I used [this html plugin](https://www.npmjs.com/package/html-webpack-plugin) to generate an `index.html` file that has all the right imports. Other stuff I did is really just dependent on my specific use case (not being isomorphic, having a debug server, minifying only for production). Oh one other thing I have found helpful, that I am surprised not everyone does, is to use environmental variables as flags, to to turn on and off stuff like debugging and minifying in your webpack config file.

**Comment by stevepiercy** [comment]
I found the source of the tilde `~` syntax under [less-loader](https://github.com/webpack/less-loader#imports).

> Can you import other resources from your node_modules folder? Like JS libraries?

Yup. I successfully completed the entire tutorial of [SurviveJS](http://survivejs.com/), if that's what you mean. (BTW, that's an excellent resource, so I bought 5 copies of the book to give out to colleagues. Christian Alfoni, the author of the guide to which your referred earlier, was one of the principal collaborators with the author. I think it's a vast improvement.)

I did not change `resolve.modulesDirectory`, assuming that would be done only in `webpack.config.js`, which is at the root of my project. The `context` should be the root, too, and the directory `/node_modules/` at the root contains everything that I have installed via npm. `bootswatch` is in there.

So I checked my `package.json` file, and discovered that there was no entry for bootswatch. WTF? :confused:

I checked my command history, and I sure did use this:

```
npm install bootswatch --save-dev
```

But I think at some point in my early forays into webpack, I used `-g` to install bootswatch. I have been told never do that, even though almost every freaking tutorial and project says to do so because it makes it easier for newbs to use the CLI. :angry: 

So to remedy the situation, I hit it with the uninstall hammer, then reinstalled.

```
npm uninstall bootswatch
npm install bootswatch --save-dev
```

Lo and behold what appears in my `package.json`!

```
    "bootswatch": "^3.3.5",
```

I also had to install bootstrap via npm.

```
npm install bootstrap --save-dev
```

Now I can use the sexy `~` for imports as in your example.

```
@import "~bootstrap/less/bootstrap.less";
```

The link you provided to [html-webpack-plugin](https://www.npmjs.com/package/html-webpack-plugin#writing-your-own-templates) was very timely, specifically my config was missing this little gem:

```
    inject: 'body' // Inject all scripts into the body 
```

...which does exactly what it says with the appropriate hash.

Man, I've learned a lot this week! My head :boom: 

Thanks for your help, encouragement, and rubber ducking.

**Comment by saulshanabrook** [comment]
@stevepiercy Ill check out Survive JS. Glad you got it working! Just today actually, I am trying a method of not using the less loader, but just requiring the CSS file directly. This saves a bunch on build time, but right now it is failing, because the css files have relative references to font files that are not being resolved properly. Once I clear those up, I will let you know if that method works.

**Comment by LukeTillman** [comment]
In case anyone finds this issue later, I was able to get the relative paths to resolve by using a custom resolver plugin like this:

```js
// Plugin to help resolve bootswatch relative paths
var BootswatchPlugin = {
  // Apply plugin to the resolver
  apply: function(resolver) {
    // Part of the path to bootswatch files
    var bootswatchPath = 'node_modules' + path.sep + 'bootswatch' + path.sep;
    
    // Plugin will process files
    resolver.plugin('file', function(request, callback) {
      // Look for requests that are relative paths inside bootswatch
      if (request.path.indexOf(bootswatchPath) !== -1 && request.request.startsWith('..')) {
        // Resolve relative to the bootstrap CSS folder instead
        var newRequest = {
          path: path.resolve(request.path, '../../bootstrap/dist/css'),
          request: request.request,
          query: request.query,
          directory: request.directory
        };
        this.doResolve(['file'], newRequest, callback);
      } else {
        callback();
      }
    });
  }
}
```

And then in `webpack.config.js`, use the custom plugin with the `webpack.ResolverPlugin`:

```js
module.exports = {
  // ... webpack config ...
  plugins: [
    // ... other plugins ...
   new webpack.ResolverPlugin([ BootswatchPlugin ])
  ]
}
```

The resolver APIs have changed pretty drastically in webpack 2.0+ (currently in beta) so you'd have to rework this if you're using that version. (Although I suspect something similar is possible even with the new APIs).

**Comment by Rajiv-Kulkarni** [comment]
I followed the steps here:
http://www.saulshanabrook.com/bootswatch-in-webpack/

I am trying to use the react-slingshot starter and getting this error after npm start:
ERROR in .//css-loader!.//less-loader!.//bootswatch/yeti/bootswatch.less
Module build failed: .box-shadow is undefined
@ C:\ReactJS\react-slingshot-master\react-slingshot-master\node_modules\bootswatch\yeti\bootswatch.less (line 25, column 4)
near lines:
border-top-color: @dropdown-divider-bg;
.box-shadow(none);
}
@ .//bootswatch/yeti/bootswatch.less 4:14-101 13:2-17:4 14:20-107
Child html-webpack-plugin for "index.html":

My About page in the demo app looks like this:
import React from 'react';
import {Link} from 'react-router';
import '../../node_modules/bootstrap/less/bootstrap.less';
import '../../node_modules/bootswatch/yeti/variables.less';
import '../../node_modules/bootswatch/yeti/bootswatch.less';
import '../styles/about-page.css';

// Since this component is simple and static, there's no parent container for it.
const AboutPage = () => {
return (

About



This example app is part of the React-Slingshot
starter kit.


Click this bad link to see the 404 page.


);
};
export default AboutPage;

Am I doing anything wrong here?

Thanks for any help.

**Comment by Rajiv-Kulkarni** [comment]
![image](https://cloud.githubusercontent.com/assets/12962858/21151766/42b9d9fc-c129-11e6-9e44-caf932fbfd00.png)

**Comment by oskarnrk** [comment]
The article written by @saulshanabrook with the link broken can be found here: 
[https://saulshanabrook.herokuapp.com/bootswatch-in-webpack/](https://saulshanabrook.herokuapp.com/bootswatch-in-webpack/)

**Comment by saulshanabrook** [comment]
@oskarnrk Wow I didn't even realize that server was still going! Looks like I forgot to port that one to medium.

**Comment by oskarnrk** [comment]
@saulshanabrook I found it with the "saulshanabrook bootswatch" query on Google :) If you port the article on Medium can you please post the new url here? :) Thank you!

**Comment by saulshanabrook** [comment]
Sure! I will probably not, out of laziness =P

**Comment by RustyRaptor** [comment]
I would just like to point out that this no longer really works because bootswatch uses scss not less. When I do use the sass loaders and load bootstrap then the bootswatch theme in that order though it also doesn't work. It seems to just load vanilla bootstrap. Or am I wrong? I don't see the less files anywhere int he package.
