### ISSUE TITLE
3.3.5 missing fonts folder

### ISSUE THREAD

**Issue by illepic** [thomaspark/bootswatch#493]
The Bootswatch 3.3.5 npm package is missing the fonts folder, causing references to `fonts/glyphicons-halflings-regular.eot` to throw errors in things like Webpack.

**Comment by illepic** [comment]
.bowerrc doesn't appear to make it over via `npm install --save`. And since .bowerrc includes the postinstall script, we don't get the fonts.

**Comment by thomaspark** [comment]
Hey @illepic, the .bowerrc script is mainly for my own use. When I use bower to update Bootstrap in the repo, the postinstall script will then copy the font files over.

Reason you're not getting the fonts is because npm is stuck on an earlier version. I can't bump until there's a new version (unlike bower which recognizes the build number e.g., v3.3.5+2). You'll have to copy the font files over for now, but it should be fixed in the next version.

**Comment by illepic** [comment]
Thanks @thomaspark! Good to know! I went ahead and copied that cp command into my own package.json postinstall entry for now.
