### ISSUE TITLE
Alert/Modal does not close on first tap on iOS device

### ISSUE THREAD

**Issue by adamhartford** [thomaspark/bootswatch#503]
Hi, I was able to reproduce this on mobile Safari and Chrome for iOS (device only). When you tap the X button on an alert or modal dialog, it requires two taps to close. The first tap sets the X's opacity to 1. The second tap fires the close event. You can also see this behavior on the alerts at www.bootswatch.com.

I'm working around the problem for now by removing the following style:

```css
.close:hover,.close:focus{opacity:1}
```

**Comment by thomaspark** [comment]
Turns out to be these code preview buttons <img width="29" alt="screen shot 2015-08-31 at 4 30 51 pm" src="https://cloud.githubusercontent.com/assets/900407/9589640/aeaa019e-4ffd-11e5-9138-f02b9a5d65c5.png">. On desktop, they display on hover. On mobile, they display on the first tap, forcing a second tap to close alerts.

This only affects Bootswatch's preview pages. You should be ok if you use the themes on your own: http://jsbin.com/megijibole/edit?output

**Comment by adamhartford** [comment]
Maybe it's not your issue, but I can reproduce it using the bootstrap fixed nav example + bootswatch. Doesn't happen with the standard bootstrap theme. View this fiddle on you iOS device:

https://jsfiddle.net/vsu2jd7s/2/

**Comment by thomaspark** [comment]
Weird, I tried it in Safari on simulator and iPhone, and both took 1 tap to close the alert.

**Comment by adamhartford** [comment]
Yeah, it doesn't happen on the simulator, just an actual device. I tried that fiddle on two iPhones and two iPads and can always reproduce it. All are running iOS 8.4.1 FWIW. I don't remember this being an issue before, so maybe related to a WebKit change? Or maybe I'm just crazy :)

**Comment by adamhartford** [comment]
FYI, just tried my fiddle again after upgrading some devices to iOS 9. Now it works as expected. Still doesn't close on first tap on my iOS 8.4.1 devices though.
