### ISSUE TITLE
overlapping

### ISSUE THREAD

**Issue by wifiextender** [thomaspark/bootswatch#567]
[overlaps](https://github.com/thomaspark/bootswatch/blob/gh-pages/paper/_bootswatch.scss#L164) the default vertical and horizontal [paddings](https://github.com/thomaspark/bootswatch/blob/gh-pages/paper/_variables.scss#L91)

![2016-05-08-234152_279x48_scrot](https://cloud.githubusercontent.com/assets/4725121/15100581/c032866e-1575-11e6-834e-1dae47b847cc.png)

![2016-05-08-234220_282x50_scrot](https://cloud.githubusercontent.com/assets/4725121/15100582/c050a70c-1575-11e6-928a-06aa9947eab8.png)

**Comment by thomaspark** [comment]
Is the "Ask me anything" a text input with custom styles?

**Comment by wifiextender** [comment]
Hello Thomas,

No it isn't. 

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>hoho</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://bootswatch.com/paper/bootstrap.min.css">
</head>
<body>

    <div class="input-group">
      <input type="text" class="form-control" placeholder="Ask me anything">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <span>&gt;&gt;</span>
          </button>
        </div>
    </div>

</body>
</html>
```

Here's [jsfiddle](https://jsfiddle.net/3fgm9bxr/) with the above code.

Cheers

**Comment by thomaspark** [comment]
Ah I see, thanks.

Yes, removing the padding on text inputs and textareas is intentional. This is in line with the Material Design style guidelines here: https://www.google.com/design/spec/components/text-fields.html#text-fields-input

The reason they are overridden instead of changing the value of `$padding-base-vertical` and `$padding-base-horizontal` is that these are also used elsewhere like for buttons.

**Comment by wifiextender** [comment]
Hey Thomas,

Thank you for the explanation.

Cheers
