### ISSUE TITLE
Ripple/Ink effect not working in chrome 51.0.2704.79 m

### ISSUE THREAD

**Issue by bjdash** [thomaspark/bootswatch#570]
Updated chrome today to version 51.0.2704.79 m and noticed that the Ripple or the Ink effect is not working anymore

**Comment by thomaspark** [comment]
Thanks for the bug report.

In the latest Chrome, passing `background-size` a single value results in the second value being set to `auto`, instead of matching the first value as in earlier versions. See: https://bugs.chromium.org/p/chromium/issues/detail?id=616072

Setting both values for `background-size` should fix this.
