### ISSUE TITLE
Why not identical html code in each template (index.html)

### ISSUE THREAD

**Issue by jipexu** [thomaspark/bootswatch#611]
Hi 
i have a question.
http://bootswatch.com/4-alpha/xxx/
In the presentation of the skins (except the top menu) why the html code is not exactly identical. For the navbar section for example we have a different code at the same position (the third navbar varies according to the themes). I think it is destabilizing because the users navigates the different themes to compare the rendering. So in my opinion the html should be strictly identical (except the fixed top menu) in the template (index.html). ..or i missed something ?..
Thanks

**Comment by thomaspark** [comment]
Ideally you'd want identical markup, but due to a change in how v4 works, some of the demo navbars become unhelpful as demos.

In v3, you simply had two classes `.navbar-default` and `.navbar-inverse`.

In v4, you combine a background class (`.bg-primary`, `.bg-faded`, `.bg-inverse`) with a color class (`.navbar-dark` or `.navbar-light`). For dark themes (and light themes that use a light navbar), the combination of bg and color classes have to be reversed. Otherwise, to make it work you end up with confusion like `.navbar-dark`using a light color.

With that said, I'm open to other solutions that will keep the markup uniform.

**Comment by thomaspark** [comment]
Closing in favor of #623.
