### ISSUE TITLE
Paper File Input Issue

### ISSUE THREAD

**Issue by rhuanbarreto** [thomaspark/bootswatch#626]
On Paper we can use the code from Ryan Walters to have floating labels working, but this break file inputs.

How can I solve this?

**Comment by thomaspark** [comment]
Can you post a demo of what you're seeing and what you expect to see? Thanks.

**Comment by rhuanbarreto** [comment]
[Fiddle with current Paper file input](http://jsfiddle.net/br80n8an/embed/)
[Desired file input](http://jsfiddle.net/uucjzaok/embed/)

**Comment by thomaspark** [comment]
Thanks. The first link shows the file input as unstyled, but is there anything else broken about it?

It's tricky to style file inputs like other buttons without doing some hacky stuff, which is why Bootstrap leaves them as is too:

<img width="223" alt="screen shot 2017-03-07 at 11 46 57 am" src="https://cloud.githubusercontent.com/assets/900407/23667434/d21b9b32-032b-11e7-9f67-2eaa456383b2.png">

If you really want to make them consistent, something you can do on your own is hide the file input and put a standard button in its corresponding label:

http://jsfiddle.net/bootswatch/80L3pk29/
