### ISSUE TITLE
navbar-brand has fixed height.

### ISSUE THREAD

**Issue by N6REJ** [thomaspark/bootswatch#653]
It's unlikely that a "brand" will ever be exactly 65px.  It's much safer just to allow it to resize with the content.
setting it to "auto" works perfectly in both situations.
![image](https://cloud.githubusercontent.com/assets/1850089/25281719/d192cf44-2673-11e7-96e1-510b22490709.png)

**Comment by thomaspark** [comment]
Agree that auto will usually work fine but height is set due to how Bootstrap 3 works.

**Comment by N6REJ** [comment]
Can you explain more about how BS3 and that height are important to not have auto?

**Comment by thomaspark** [comment]
BS3 made the decision to set navbar-brand height based on variable:

```less
.navbar-brand {  
  height: @navbar-height;
}
```

Since Bootswatch uses BS to generate themes, they'll all have a set value as well. We could have the themes override it and set it to `auto`, but the tradeoff is now you have an extra rule, and you reduce parity with plain BS. So we leave it up to the theme users to override if they find it necessary.

However, BS4's navbar-brand height is not explicitly set, so it'll be closer to what you have in mind.

**Comment by N6REJ** [comment]
ah! ok, That explains alot.. yeah, I see in bs4 they've "fixed" alot of the trivial things... I'm really looking forward to BS4, I mix flex and bs3 alot as it is depending on which does the job best for that container.
