### ISSUE TITLE
Why not to keep Bootstrap and Bootswatch CSS separate?

### ISSUE THREAD

**Issue by praisedpk** [thomaspark/bootswatch#670]
Why not to keep Bootstrap and Bootswatch CSS separate? That will be much more Opensource CDN friendly, and HTTP/2 will cover the cost of 2 separate CSS files.

What I mean is that each theme to have just its specific CSS code and Bootstrap is loaded separately by the themes from bower_components directory.

Any such plans for Bootstrap/Bootswatch 4, or if it is possible at all with Bootswatch?
Thanks.

**Comment by thomaspark** [comment]
Hey @praisedpk, the reason we don't do that is most themes have more extensive changes that require a rebuild instead of just a few css overrides. To separate it into its own css file would duplicate a lot of unnecessary code but also make it much more work to create the themes than changing the value of less/sass variables.
