### ISSUE TITLE
File path not visible with custom browse button, too strong indentation in every text field

### ISSUE THREAD

**Issue by MaEtUgR** [thomaspark/bootswatch#806]
We have a page to upload and analyze drone autopilot flight logs https://logs.px4.io/ which started using https://bootswatch.com/yeti/ and there is are two cosmetic issues related to the theme which I explained in detail here (with a screenshot): https://github.com/PX4/flight_review/issues/93

Is there any known solution or support for solving these issues?
FYI @bkueng

**Comment by thomaspark** [comment]
Hey @MaEtUgR, cool site.

I'll reduce the padding on inputs since it's causing people to think there are extra spaces.

As far as showing the file name, instead of using your own browse button, you can unhide the file input to get back that functionality. Or if you prefer to use your own button, you'll need to use JS to grab the input's value and insert it somewhere.

**Comment by MaEtUgR** [comment]
@thomaspark Thanks a lot! 👍
