### ISSUE TITLE
Darkly primary text

### ISSUE THREAD

**Issue by neobie** [thomaspark/bootswatch#963]
Thanks for the wonder theme.

I have some suggestions here.
I am wondering why text-primary is unreadable / unnoticeable.
Text is  too dark, but text-primary suppose to be clear and capture attention quickly.

And also for table-light row, the color suppose to be 'lightweight' (nearly same as background) instead of very 'bright' ?

This could make switching day / night mode better.

**Comment by thomaspark** [comment]
Hey @neobie,

`text-primary` and `table-light` are derived from variables `$primary` and `$light`.

For `text-primary`, I agree that as text it's tough to read, but since it's based on the predominant color used in the navbar and buttons, we'll keep it as primary. I recommend a higher contrast like `text-info` for your case.

For `table-light`, since there's both a `$light` and `$dark` variable, it makes more sense to keep `$light` has a brighter color, rather than a low-contrast darker color for dark themes, to avoid confusion. `table-dark` will work instead.
